name: sessionize-new-proposal

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  # Setting an environment variable with the value of a configuration variable
  SESSIONIZE_LATEST_SESSION_ID_PREVIOUS: ${{ vars.SESSIONIZE_LATEST_SESSION_ID }}

jobs:
  retrieve-latest-session:
    name: retrieve-latest-session
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve latest session
      env:
        SESSIONIZE_SESSION_LIST_URL: ${{ secrets.SESSIONIZE_SESSION_LIST_URL }}
      run: |
        SESSIONIZE_LATEST_SESSION_ID=$(curl -s $SESSIONIZE_SESSION_LIST_URL | jq -r '.[].sessions[].id' | sort -u | tail -n 1)
        if [ "$SESSIONIZE_LATEST_SESSION_ID_PREVIOUS" -eq "$SESSIONIZE_LATEST_SESSION_ID" ]; then
          echo "No new sessions"
        else
          echo "New session: $SESSIONIZE_LATEST_SESSION_ID"
        fi
