name: sessionize-new-proposal

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  # Setting an environment variable with the value of a configuration variable
  SESSIONIZE_LATEST_SESSION_ID_PREVIOUS: ${{ vars.SESSIONIZE_LATEST_SESSION_ID }}

jobs:
  retrieve-latest-session:
    name: retrieve-latest-session
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve latest session
      env:
        SESSIONIZE_SESSION_LIST_URL: ${{ secrets.SESSIONIZE_SESSION_LIST_URL }}
      run: |
        SESSIONIZE_LATEST_SESSION_ID=$(curl -s $SESSIONIZE_SESSION_LIST_URL | jq -r '.[].sessions[].id' | sort -u | tail -n 1)
        if [ "$SESSIONIZE_LATEST_SESSION_ID_PREVIOUS" -eq "$SESSIONIZE_LATEST_SESSION_ID" ]; then
          exit 0
        else
          echo "New session: $SESSIONIZE_LATEST_SESSION_ID"
          SESSIONIZE_NEW_SESSIONS=$(curl -s $SESSIONIZE_SESSION_LIST_URL | jq -r --arg SESSIONIZE_LATEST_SESSION_ID_PREVIOUS "$SESSIONIZE_LATEST_SESSION_ID_PREVIOUS" '[.[].sessions[] | select(.id > $SESSIONIZE_LATEST_SESSION_ID_PREVIOUS) | {id,title,description}]')
          echo $SESSIONIZE_NEW_SESSIONS | jq -c '.[]' | while read -r object; do
            curl --location "$SLACK_WEBHOOK_URL" --header 'Content-Type: application/json' --data "$object" -v
            sleep 5
          done
        fi
